import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar/navbar";
import LoginModal from "./components/modals/LoginModal";




export const metadata: Metadata = {
  title: "Django AirBnb",
  description: "Generated by create next app",
};

const content = (
  
    <p>yo</p>
  )

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        <div className="pt-32">
          {children}
        </div>
        <LoginModal/>
        
        </body>
    </html>
  );
}
