# Generated by Django 5.2.8 on 2026-09-28 12:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoversationMessage',
            new_name='ConversationMessage',
        ),
    ]
