# Generated by Django 5.2.8 on 2026-09-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(default='uncategorized', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='country_code',
            field=models.CharField(max_length=10),
        ),
    ]
